### ISSUE TITLE
Suggested .net API compatibility level (2.0 Subset) is not available in Unity 2018.3

### ISSUE THREAD

**Issue by jungleeToofan** [google/play-instant-unity-plugin#127]
Clicking the 'Update' button in Play Instant Player Settings sets the API compatibility level to .net 4.x

**Comment by thanwah** [comment]
I've submitted a fix to the master branch for this. It might be a week or more before I create a new release, however.

It turns out that in 2018.3 the 2.0 Subset is still relevant if you set the Scripting Runtime Version to .NET 3.5 (which is deprecated). New settings were required for the .NET 4.x runtime.

Thanks again for the bug report!

**Comment by jungleeToofan** [comment]
Great! Happy to help :)
