### ISSUE TITLE
Error parsing a meta element's content: ';' is not a valid key-value pair separator.

### ISSUE THREAD

**Issue by hicosmonaut** [google/play-instant-unity-plugin#21]
Hello, I want to work with your plugin but I have some problems. So, I did all about you write in manual and start to build test apk, after that I launch my app and open a browser and go to _https_(or _http_)_://instant.apps/com.product.name_ and nothing happens. I start to see logs via adb and find that string:

_08-01 10:51:57.391: I/chromium(12647): [INFO:CONSOLE(1)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: http://instant.apps/com.product.name(1)_

Can you help me please?

For tests I create some libraby with empty activity:

```
<activity android:name="com.product.TestActivity">
    <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.BROWSABLE" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:scheme="http" />
        <data android:scheme="https" />
        <data android:host="instant.apps" />
        <data android:path="/${applicationId}" />
    </intent-filter>
</activity>
```
And also I tried it with/without this:
`<meta-data android:name="default-url" android:value="https://instant.apps/${applicationId}" />`

**Comment by thanwah** [comment]
Hi, thanks for trying the plugin and for reaching out.

There are two options for configuring the URL that will launch your instant app:
1. Developer specified URL: provide your own URL in the AndroidManifest and [prove that you own the website](https://developer.android.com/training/app-links/verify-site-associations#web-assoc)
1. Automatic URL: do not specify a URL in the AndroidManifest

It sounds like you're trying to use the second approach. In this case you should remove the VIEW intent filter and "default-url" meta-data related to "https://instant.apps" from your AndroidManifest.

After you publish your app in Play Console, the URL https://instant.apps/your.package.name will automatically open your instant app. However, before you publish and while you're testing locally, the https://instant.apps URL will not open your instant app.

If you want to test your app prior to publishing, you can use the "Build and Run" feature of the plugin or you can directly run the command that it calls:

`android-sdk/extras/google/instantapps/ia run instant-app.apk`

**Comment by hicosmonaut** [comment]
Thank you for your help! I have another question "Build and Run" feature doesn't help me and I run 
`android-sdk/extras/google/instantapps/ia run instant-app.apk` 

So, `instant-app.apk` is a full release apk with instant app inside or just instant app module?

**Comment by thanwah** [comment]
I'm sorry to hear that the "Build and Run" feature isn't working for you. Do you mind sharing the error message that it is printed to the Unity console log as well as the version of Unity that you're using?

Regarding instant app APKs/modules:
- An instant app and a full release app are both packaged in APKs.
- There is not much that is special/different about an instant app except some additional requirements for the manifest and for signing (the Unity plugin takes care of these requirements when building an instant app).
- A typical Unity instant app is only a single APK (you could think of it as a single module).
- In the example "instant-app.apk" is not a full release apk with instant app inside, it's just an Android app that was built with a couple minor changes to support instant. This APK can be run as an instant app using "ia run", or since it's just an APK, it can be installed and run as a regular app, i.e. "adb install instant-app.apk". Note: I mention this to hopefully clarify that it's just like a regular APK, not because this is typically done.

**Comment by thanwah** [comment]
Closing this issue. If there is still a problem, please resubmit here: https://github.com/google/play-unity-plugins/issues
