### ISSUE TITLE
Failed to locate ia.jar

### ISSUE THREAD

**Issue by caneva20** [google/play-instant-unity-plugin#8]
Hi, I was trying the plugin, but when I hit Build and Run (from PlayInstant menu) I'm getting this error

`Build and Run failed to locate ia.jar file at: C:/Users/Fabricio/AppData/Local/Android/sdk\extras/google/instantapps/tools/ia.jar`

One other thing that I've noticed is that the folder `tools` under `extras/google/instantapps` does not exist,
so I tried to install the SDK again, and that was what I got

`PlayInstantSdkInstaller: The Instant Apps Development SDK package is already installed at the latest available version (1.3.0)`

Is that a bug or am I doing something wrong?

[sdkmanager.bat --list](https://gist.github.com/caneva20/6ed18a73553e4fec552aba0579f42d07)

**UPDATE** :)

Well, I've done a little bit more research here and I "fixed" the problem now, but I did it totally by hand (I mean that was not the plugin) and I still think this is a valid issue. What I did was to open SDK manager and check for the packages listed [here](https://developer.android.com/topic/google-play-instant/getting-started/first-instant-app), the `Instant Apps Development SDK` was not really installed, then, but after the installation the build was still failing with the same error, I checked again the folder (extras/google/instantapps) and the `tools` folder was still missing, alright, fine, so I've gone the the "root" sdk folder and I noticed another folder called `andriod-sdk` (not `sdk`.) it has a similar structure to the sdk folder and there was the folder `extras/google/instantapps/tools`, but only this folder (with the ai.jar and other files) them I copied this folder to `sdk/extras/google/instantapps` and voila, it worked. \o/

Above I was just describing what I did. is not too relevant, the problem I see is that the plugin is not installing the sdk properly nor the SDK manager.

**Comment by thanwah** [comment]
Hi Fabricio, thank you for reporting this issue. I'm glad that you were able to get it to work by manually copying the ia.jar file.

Based on your output from "sdkmanager.bat --list" it seems like sdkmanager was in a state where it thought the package "extras;google;instantapps" was installed at the latest version (1.3), but in reality there were some files missing.

Offhand I'm not sure how the Android SDK could get in this state without manually removing the files in question. Perhaps a partially completed but then aborted or failed install?

For anyone else who might experience this, one quick workaround is to delete everything in the extras/google/instantapps folder and then re-run the "Set up Instant Apps Development SDK" menu option to reinstall the latest version of the instant apps tools.

Since it's working for you now, I'm going to go ahead and close this issue.

If anyone else experiences this issue, please let us know so we can investigate further. Thanks.
